[package]
name = "win_test"
version = "0.1.0"
authors = ["Thomas <thomas@etnur.net>"]
edition = "2018"
[dependencies]
log = "*"
stderrlog = "*"
csv = "1"
regex = "1"
lazy_static = "*"
clap = "*"
[target.'cfg(windows)'.dependencies]
winapi = { git = "https://github.com/retep998/winapi-rs.git", branch = "0.3", features = ["winuser", "handleapi","fileapi"] }
# winapi = { version = "0.3", features = ["winuser", "handleapi","fileapi"] }
[target.'cfg(windows)']
wmi = { git = "git@github.com:ohadravid/wmi-rs.git" }