log_level: 'trace'
log_dest: 'Stderr'
# log_dest: 'stream'
# log_stream: 'debug.log'
mod_level: 
  'common::config::migrate': 'debug'
  # 'common::wifi_config': 'trace'
  'linux_migrator': 'trace' 
  # 'linux_migrator::migrate_info': 'trace' 
