log_level: 'warn'
modules: 
#  - name: balena_migrate::migrator::common::config
#    level: 'info'
#  - name: 'balena_migrate::migrator::common'
#    level: 'trace'  
 - name: 'balena_migrate::migrator::linux'
   level: 'trace'  