log_level: 'trace'
log_dest: 'Stderr'
# log_dest: 'stream'
# log_stream: 'debug.log'
mod_level: 
  'common' : 'info'
  'common::wifi_config' : 'warn'
  'mswin' : 'info'
  'mswin::migrate_info' : 'debug'
  'mswin::wmi_utils::mount_point' : 'debug'
  'mswin::wmi_utils::volume' : 'debug'
  'linux' : 'info'
  # 'linux::migrate_info' : 'debug'
  # 'common::config::migrate': 'debug'
  # 'mswin::win_api' : 'info'
  # 'mswin::win_api::wmi_api' : 'info'
  # 'mswin::win_api::iwbem_class_wr' : 'info'
  # 'mswin::win_api::wmi_api::com_api' : 'info'
  # 'mswin::wmi_utils::logical_drive' : 'info'
  # 'common::wifi_config': 'trace'
  # 'linux_migrator': 'trace' 
  # 'linux_migrator::migrate_info': 'trace' 
