log_level: 'warn'
log_dest: 'stderr'
# log_dest: 'stream'
# log_stream: 'debug.log'
modules: 
 - name: common::config
   level: 'info'
#  - name: 'common'
#    level: 'trace'  
 - name: 'linux'
   level: 'trace'  
