migrate:
  mode: IMMEDIATE
  all_wifis: true
  reboot: 10
  log_to:
    drive: "/dev/sda1"
    fs_type: ext4
  kernel_file: "balena_x86_64.migrate.kernel"
  initramfs_file: "balena_x86_64.migrate.initramfs"
  backup: 
  internal:
  # internal migrate information intended for stage 2
    stage2_home: ""
balena:
  image: image.gz
  config: config.json  
  api: 
    host: "api.balena-cloud.com"
    port: 443
    check: true
  vpn:
    host: "api.balena-cloud.com"  
    port: 443
    check: true
  check_timeout: 20
debug:
  fake_admin: true

        