migrate:
  mode: IMMEDIATE
  home_dir: './work/'
  all_wifis: true
  wifis: 
    - 'Xcover'
    - 'QIFI'
    - 'bla'
  reboot: 10
  
  log_to:
    drive: "/dev/sda1"
    fs_type: ext4
  kernel_file: "balena_x86_64.migrate.kernel"
  initramfs_file: "balena_x86_64.migrate.initramfs"
  backup: 
balena:
  image: image.gz
  config: config.json
  app_name: 'test' 
  api: 
    host: "api.balena-cloud.com"
    port: 443
    check: true
  vpn:
    host: "api.balena-cloud.com"  
    port: 443
    check: true
  check_timeout: 20
debug:
  fake_admin: true
  fake_flash_device: '/dev/sdb'

        